title: "Profile Block"
status: "in-progress"
preview: "@preview"
context:
  title: "Michael Luttrell: Keeping campus safe during COVID"
  url: "https://news.ucsc.edu/2021/08/michael-luttrell-outstanding-staff.html"
  image: "https://news.ucsc.edu/2021/08/images/michaelluttrell-featured.jpg"
  teaser: "Michael Luttrell, this year’s Outstanding Staff Award winner, worked hard to keep the campus safe during a chaotic year of pandemic fears and a devastating wildfire."
